### ISSUE TITLE
Enforce HTTPS

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/fakeiteasy.github.io#34]
Like GitHub [says we can](https://github.com/blog/2186-https-for-github-pages)

[![image](https://cloud.githubusercontent.com/assets/3275797/15906538/47152b9a-2d87-11e6-92fd-cd084fe3483a.png)](https://github.com/FakeItEasy/fakeiteasy.github.io/settings)

**Comment by blairconrad** [comment]
Anyone think this is a bad idea?

**Comment by thomaslevesque** [comment]
I don't see any reason not to do it

**Comment by blairconrad** [comment]
Done!

**Comment by blairconrad** [comment]
Thanks, @thomaslevesque!

**Comment by adamralph** [comment]
:+1:
