### ISSUE TITLE
Use new logo and favicons

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/fakeiteasy.github.io#5]
Spun off from #4. It's be nice to have something that's a little more scalable.

**Comment by blairconrad** [comment]
With favicons courtesy http://realfavicongenerator.net/?

**Comment by adamralph** [comment]
:+1:

**Comment by danielmarbach** [comment]
What happened to @philippdolder and @bbvch sponsoring the logo? Is it time for me to punch someone in da face;)?

**Comment by adamralph** [comment]
@danielmarbach we hadn't heard anything for almost a year so we, or at least I, assumed the initiative had stalled.

We wanted to have a new logo for the 2.0 release, which is rapidly nearing readiness (it's been through several beta iterations already), so we decided to explore other avenues and we now have a new logo which is in the final stages of tuning. If the bbv initiative ever gets restarted then we may consider a new logo for a future major release but my preference for 2.x is to stick with the logo we are currently working with.

**Comment by danielmarbach** [comment]
Didn't you guys have an appointment in zug to kickstart everything?

**Comment by adamralph** [comment]
Yep, see above :wink:

**Comment by blairconrad** [comment]
**Discussion moved from** FakeItEasy/FakeItEasy#391

I whipped this up:

![image](https://cloud.githubusercontent.com/assets/3275797/5989264/7fbca6ac-a94f-11e4-93a5-64b985c960ac.png)

The logo should probably be moved over to align with the code block below it…

**Comment by adamralph** [comment]
Looks great!

I wonder if it might be better with the tag line immediately following the logo (bottom aligned), instead of being over on the right.

**Comment by blairconrad** [comment]
It would probably look like this.

![image](https://cloud.githubusercontent.com/assets/3275797/5989796/45c27924-a961-11e4-80f5-bb1c4d6616c6.png)

**Comment by adamralph** [comment]
Looks great to me. You want to whip up a PR?

**Comment by blairconrad** [comment]
Gladly. The CSS needs tidying, but I'll get something out in a day or two.

**Comment by adamralph** [comment]
I just spotted one problem with the latest changes, the docs button points to https://github.com/FakeItEasy/fakeiteasy.github.io/wiki instead of https://github.com/FakeItEasy/FakeItEasy/wiki

**Comment by blairconrad** [comment]
Oh. That's not so good. I'll remove the jekyll variable interpolation and put a proper hardcoded link in.

**Comment by adamralph** [comment]
If we want to investigate SVG then we can raise another issue.
