### ISSUE TITLE
Host the generated FakeItEasy.Analyzers docs on the FakeItEasy website

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/fakeiteasy.github.io#54]

**Comment by blairconrad** [comment]
Current URL

https://fakeiteasy.readthedocs.io/projects/analyzers/en/stable/

Proposal:
https://fakeiteasy.github.io/docs/analyzers/en/stable/

@thomaslevesque, any objection to this URL? I'm open to alternatives for the "analyzers" segment (or most of the rest).

Also, we'll eventually have to decide where to put the main FIE docs. With the above URL, just hosting the main docs at 

https://fakeiteasy.github.io/docs/en/stable/

_might_ cause conflicts? TBH I'm not sure. I guess only if we have an article called "en" (or pick your favourite language code).

If we want to entertain that URL, I guess we could be thinking of 

* https://fakeiteasy.github.io/docs/en/stable/
* https://fakeiteasy.github.io/docs/main/en/stable/
* https://fakeiteasy.github.io/docs/fie/en/stable/
* https://fakeiteasy.github.io/docs/fakeiteasy/en/stable/

Or something else I can't think of right now. Have you any preferences?

**Comment by thomaslevesque** [comment]
Your proposal sounds good to me, except for the `/en` part. We don't have docs in multiple languages, so why include the language in the URL?

> With the above URL, just hosting the main docs at
> 
> https://fakeiteasy.github.io/docs/en/stable/
> 
> _might_ cause conflicts?

I wondered about that, but I think it should be fine. We'll need to try to be sure.

If it causes issues, I'd go with https://fakeiteasy.github.io/docs/fakeiteasy/stable and https://fakeiteasy.github.io/docs/analyzers/stable

**Comment by blairconrad** [comment]
Steps for adding the docs:

1. check out FakeItEasy.Analyzers (I used master, since its docs have the 6.1.0 content and the material for mkdocs styling)
2. ensure the proper python packages are installed (feel free to use a virtual environment):
```powershell
pip install -r docs/requirements.txt
```
3. check out fakeiteasy.github.io
4. create `host-analyzers-docs` branch from upstream/master. Do not switch to it. Stay on master
5. add the docs
```powershell
mike deploy 6.1 stable --branch host-analyzers-docs --prefix docs/analyzers --update-aliases --config-file ..\FakeItEasy.Analyzers\mkdocs.yml
```
this will add docs for 6.1 with the alias "stable" pointing at them, and commit on the host-analyzer-docs branch
