### ISSUE TITLE
backfill all the FakeItEasy docs versions that we feel like, adding them to this repo

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/fakeiteasy.github.io#61]

**Comment by blairconrad** [comment]
Like #59, only for historical documents.

I'd also like to update links to the analyzers docs to point at the new site as well. At least where we reference the analyzer docs. Adding an article where there wasn't one is also possible, but probably not worth the effort.

Ideally we'd translate all versions of the docs, but this may not be feasible, given how the docs have changed over time. Or maybe we can transplant them all, but with some loss of fidelity (e.g. maybe after a while, we lose the material styling, or links to other versions).

I can start the journey backward in time, seeing how it goes. One idea I have is that if it becomes possible but tedious to translate the docs, we have options to reduce the effort:

* prioritize later bugfix versions over earlier or non-bugfix versions (for example translate 7.0.2 but not 7.0.1 or 7.0.0)
* more drastically, translate only the latest version for each major number. That is 1.25.3, 2.3.3, 3.4.2, 4.9.1, 5.5.0, 6.2.1

But we'll see how it goes.

**Comment by blairconrad** [comment]
Expected script for each docs version:

Steps for adding the docs:

1. check out fakeiteasy.github.io
2. create `backfill-docs` branch from upstream/master. Do not switch to it. Stay on master
3. check out FakeItEasy at a tag that corresponds to the docs version
4. attempt to update the mkdocs config so we can build with Material for MkDocs and with mike. This may require copying in assets such as the logos
5. ensure the proper python packages are installed (feel free to use a virtual environment):
     ```bash
    pip install --requirement docs/requirements.txt  # requirements.txt updated in step 4
    ```
6. switch to fakeiteasy.github.io repo and add the docs
     ```bash
    mike deploy <version number> --branch backfill-docs --prefix docs --config-file ..\FakeItEasy\mkdocs.yml
    ```
7. `--version; goto 3`

**Comment by blairconrad** [comment]
For a lark, I converted 7.3.0 without trying to apply the Material for MkDocs theme. The result wasn't bad. It looks like the old RTD docs, but does have a version selector!

![image](https://user-images.githubusercontent.com/3275797/204536778-a6e79230-843f-453b-9696-c4aaf60917ef.png)

**Comment by thomaslevesque** [comment]
> * more drastically, translate only the latest version for each major number. That is 1.25.3, 2.3.3, 3.4.2, 4.9.1, 5.5.0, 6.2.1

I think that would be enough. In fact, what would be nice would be to have pages for 1.x, 2.x, ... 7.x, which always show the docs for the latest corresponding minor version. Not sure this is feasible, though...


> For a lark, I converted 7.3.0 without trying to apply the Material for MkDocs theme. The result wasn't bad. It looks like the old RTD docs, but does have a version selector!

It looks fine! If there's no easy way to apply the Material theme to the old docs, that's certainly good enough.

**Comment by blairconrad** [comment]
> In fact, what would be nice would be to have pages for 1.x, 2.x, ... 7.x, which always show the docs for the latest corresponding minor version

I may not quite be getting your exact intent. Tell me where I go wrong.

I don't know about redirecting "wildcard" versions, but aliasing any given string of the form 6.x.y to point to a specific 6.w.z is quite easy. Also aliasing 6 to 6.x.y.

**Comment by thomaslevesque** [comment]
I didn't mean a wildcard. I meant that instead of having a version of the docs for each minor/patch release, we could publish docs only for the latest version in each major.
As of today, `/docs/7.x/` would contain the docs for 7.3.1. If we release a 7.3.2, the docs for 7.3.2 will overwrite the docs in `/docs/7.x/`. The docs for earlier minor version wouldn't be available at all.

**Comment by thomaslevesque** [comment]
The downside of this approach is that if we add a feature in a minor version, e.g. 7.2.0, someone using 7.1.3 would see this feature in the docs but wouldn't actually be able to use it... The solution would be to maintain docs for each minor version (not patch).

**Comment by blairconrad** [comment]
OH! Completely replacing the docs, so there would be no `/docs/7.3.1` or `/docs/7.4.2`, only `/docs/7.x`? I think this would be fraught.  As you say, having `/docs/7.1.x` would be better.

Still, generating docs for every build seems like it's less likely to cause confusion, at the cost of a few MB of disk each time. And an ever-expanding list of versions in the dropdown.

**Comment by thomaslevesque** [comment]
True. Docs for every release then!
