### ISSUE TITLE
have Read The Docs redirect here for all versions

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/fakeiteasy.github.io#63]

**Comment by blairconrad** [comment]
Most versions were redirected by making them inactive and also [adding a redirect rule](https://readthedocs.org/dashboard/fakeiteasy/redirects/19689/edit/):
`/en/$rest -> https://fakeiteasy.github.io/docs/`

"latest" got another rule:
`/en/latest/$rest -> https://fakeiteasy.github.io/docs/stable/`

as did "stable":
`/en/latest/$rest -> https://fakeiteasy.github.io/docs/stable/`

However the stable branch is still served by RTD, so we'll need to push a docs update that contains a single index page that redirects to https://fakeiteasy.github.io/docs/stable/.

**Comment by thomaslevesque** [comment]
Here's a recap of what we did
- create a [new clone](https://github.com/FakeItEasy/crispy-couscous) of the FakeItEasy repo
- removed everything except:
  - readthedocs.yml
  - mkdocs.yml
  - docs/requirements.txt
- add an index.md with a script that redirects to the correct page on fakeiteasy.github.io
- Change the repo URL in ReadTheDocs, and resync the webhook
- Add a 999.0.0 tag. ReadTheDocs considers this the new stable version, and builds it
- Make the repo private

**Comment by thomaslevesque** [comment]
Also done for FakeItEasy.Analyzers (and updated the steps above, since it didn't work following the exact same steps...)
