### ISSUE TITLE
Point to the twitter account

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/fakeiteasy.github.io#7]
Because we have one now! [fakeiteasyfx](https://twitter.com/fakeiteasyfx)

We should probably point to it, because it'd be a crime for people to miss out on the scintillating tweets.

**Comment by blairconrad** [comment]
Thanks for the label cleanup. I got called away.

Also thanks for the work!

**Comment by adamralph** [comment]
I removed `up-for-grabs` when I assigned the issue to myself.

The `in-progress` is Waffle magic :sparkles: https://waffle.io/adamralph/adamralph.github.com?source=FakeItEasy%2Ffakeiteasy.github.io,FakeItEasy%2FFakeItEasy,FakeItEasy%2Ffakeiteasy-assets
